# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/D'ratius/AppData/Local/Temp/SearchUgpVgy.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 391)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Downloads/3dorange.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tvSearch = QtWidgets.QLineEdit(self.centralwidget)
        self.tvSearch.setClearButtonEnabled(False)
        self.tvSearch.setObjectName("tvSearch")
        self.gridLayout.addWidget(self.tvSearch, 0, 0, 1, 1)
        self.toEpisodeSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.toEpisodeSpinBox.setEnabled(False)
        self.toEpisodeSpinBox.setObjectName("toEpisodeSpinBox")
        self.gridLayout.addWidget(self.toEpisodeSpinBox, 9, 3, 1, 1)
        self.radioButtonFromTo = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonFromTo.setObjectName("radioButtonFromTo")
        self.gridLayout.addWidget(self.radioButtonFromTo, 10, 3, 1, 1)
        self.radioButtonFromSpecifics = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonFromSpecifics.setObjectName("radioButtonFromSpecifics")
        self.gridLayout.addWidget(self.radioButtonFromSpecifics, 11, 2, 1, 2)
        self.fromSeasonSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.fromSeasonSpinBox.setObjectName("fromSeasonSpinBox")
        self.gridLayout.addWidget(self.fromSeasonSpinBox, 7, 2, 1, 1)
        self.labelTo = QtWidgets.QLabel(self.centralwidget)
        self.labelTo.setObjectName("labelTo")
        self.gridLayout.addWidget(self.labelTo, 8, 2, 1, 1)
        self.toSeasonSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.toSeasonSpinBox.setEnabled(False)
        self.toSeasonSpinBox.setObjectName("toSeasonSpinBox")
        self.gridLayout.addWidget(self.toSeasonSpinBox, 9, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 17, 0, 1, 1)
        self.countdownLcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countdownLcdNumber.sizePolicy().hasHeightForWidth())
        self.countdownLcdNumber.setSizePolicy(sizePolicy)
        self.countdownLcdNumber.setMaximumSize(QtCore.QSize(16777215, 40))
        self.countdownLcdNumber.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.countdownLcdNumber.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.countdownLcdNumber.setLineWidth(7)
        self.countdownLcdNumber.setSmallDecimalPoint(False)
        self.countdownLcdNumber.setMode(QtWidgets.QLCDNumber.Dec)
        self.countdownLcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.countdownLcdNumber.setProperty("intValue", 65)
        self.countdownLcdNumber.setObjectName("countdownLcdNumber")
        self.gridLayout.addWidget(self.countdownLcdNumber, 1, 0, 1, 1)
        self.radioButtonSpecifics = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonSpecifics.setChecked(True)
        self.radioButtonSpecifics.setObjectName("radioButtonSpecifics")
        self.gridLayout.addWidget(self.radioButtonSpecifics, 10, 2, 1, 1)
        self.pushButtonSend = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSend.sizePolicy().hasHeightForWidth())
        self.pushButtonSend.setSizePolicy(sizePolicy)
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.gridLayout.addWidget(self.pushButtonSend, 17, 2, 1, 2)
        self.fromEpisodeSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.fromEpisodeSpinBox.setObjectName("fromEpisodeSpinBox")
        self.gridLayout.addWidget(self.fromEpisodeSpinBox, 7, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 15, 0, 1, 1)
        self.labelSeason = QtWidgets.QLabel(self.centralwidget)
        self.labelSeason.setObjectName("labelSeason")
        self.gridLayout.addWidget(self.labelSeason, 6, 2, 1, 1)
        self.webSearch = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webSearch.sizePolicy().hasHeightForWidth())
        self.webSearch.setSizePolicy(sizePolicy)
        self.webSearch.setClearButtonEnabled(True)
        self.webSearch.setObjectName("webSearch")
        self.gridLayout.addWidget(self.webSearch, 0, 3, 1, 1)
        self.labelEpisode = QtWidgets.QLabel(self.centralwidget)
        self.labelEpisode.setObjectName("labelEpisode")
        self.gridLayout.addWidget(self.labelEpisode, 6, 3, 1, 1)
        self.episodeBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.episodeBrowser.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Eras Medium ITC")
        font.setPointSize(11)
        self.episodeBrowser.setFont(font)
        self.episodeBrowser.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.episodeBrowser.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.episodeBrowser.setAutoFillBackground(False)
        self.episodeBrowser.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.episodeBrowser.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.episodeBrowser.setLineWidth(4)
        self.episodeBrowser.setObjectName("episodeBrowser")
        self.gridLayout.addWidget(self.episodeBrowser, 1, 2, 1, 2)
        self.labelWeb = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelWeb.sizePolicy().hasHeightForWidth())
        self.labelWeb.setSizePolicy(sizePolicy)
        self.labelWeb.setMaximumSize(QtCore.QSize(60, 16777215))
        self.labelWeb.setObjectName("labelWeb")
        self.gridLayout.addWidget(self.labelWeb, 0, 2, 1, 1)
        self.seasonTreeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.seasonTreeWidget.setObjectName("seasonTreeWidget")
        self.seasonTreeWidget.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.seasonTreeWidget, 2, 2, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuWindows = QtWidgets.QMenu(self.menubar)
        self.menuWindows.setObjectName("menuWindows")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.dockWidgetContents)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout.addWidget(self.calendarWidget)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionManual = QtWidgets.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.actionQuit_2 = QtWidgets.QAction(MainWindow)
        self.actionQuit_2.setObjectName("actionQuit_2")
        self.actionCalendar = QtWidgets.QAction(MainWindow)
        self.actionCalendar.setObjectName("actionCalendar")
        self.actionCheck_for_updates = QtWidgets.QAction(MainWindow)
        self.actionCheck_for_updates.setEnabled(False)
        self.actionCheck_for_updates.setObjectName("actionCheck_for_updates")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionQuit)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionCheck_for_updates)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionVersion)
        self.menuWindows.addAction(self.actionCalendar)
        self.menuWindows.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.labelTo.setBuddy(self.toSeasonSpinBox)
        self.labelSeason.setBuddy(self.fromSeasonSpinBox)
        self.labelEpisode.setBuddy(self.fromEpisodeSpinBox)
        self.labelWeb.setBuddy(self.webSearch)

        self.retranslateUi(MainWindow)
        self.radioButtonSpecifics.toggled['bool'].connect(self.toSeasonSpinBox.setDisabled)
        self.radioButtonSpecifics.toggled['bool'].connect(self.toEpisodeSpinBox.setDisabled)
        self.radioButtonFromTo.toggled['bool'].connect(self.toSeasonSpinBox.setEnabled)
        self.radioButtonFromTo.toggled['bool'].connect(self.toEpisodeSpinBox.setEnabled)
        self.radioButtonFromSpecifics.toggled['bool'].connect(self.toSeasonSpinBox.setDisabled)
        self.radioButtonFromSpecifics.toggled['bool'].connect(self.toEpisodeSpinBox.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tvSearch, self.webSearch)
        MainWindow.setTabOrder(self.webSearch, self.episodeBrowser)
        MainWindow.setTabOrder(self.episodeBrowser, self.seasonTreeWidget)
        MainWindow.setTabOrder(self.seasonTreeWidget, self.fromSeasonSpinBox)
        MainWindow.setTabOrder(self.fromSeasonSpinBox, self.fromEpisodeSpinBox)
        MainWindow.setTabOrder(self.fromEpisodeSpinBox, self.toSeasonSpinBox)
        MainWindow.setTabOrder(self.toSeasonSpinBox, self.toEpisodeSpinBox)
        MainWindow.setTabOrder(self.toEpisodeSpinBox, self.radioButtonSpecifics)
        MainWindow.setTabOrder(self.radioButtonSpecifics, self.radioButtonFromTo)
        MainWindow.setTabOrder(self.radioButtonFromTo, self.radioButtonFromSpecifics)
        MainWindow.setTabOrder(self.radioButtonFromSpecifics, self.pushButtonSend)
        MainWindow.setTabOrder(self.pushButtonSend, self.calendarWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TodaytvSeries"))
        self.tvSearch.setToolTip(_translate("MainWindow", "<html><head/><body><p>Search The Web</p></body></html>"))
        self.tvSearch.setPlaceholderText(_translate("MainWindow", "Search"))
        self.radioButtonFromTo.setText(_translate("MainWindow", "From And To Specifics"))
        self.radioButtonFromSpecifics.setText(_translate("MainWindow", "From Specific Episode (current season ONLY)"))
        self.labelTo.setText(_translate("MainWindow", "To"))
        self.countdownLcdNumber.setToolTip(_translate("MainWindow", "<html><head/><body><p>Time Till Next Release</p></body></html>"))
        self.radioButtonSpecifics.setText(_translate("MainWindow", "Specific Episode"))
        self.pushButtonSend.setText(_translate("MainWindow", "Send to IDM"))
        self.labelSeason.setText(_translate("MainWindow", "Season"))
        self.webSearch.setPlaceholderText(_translate("MainWindow", "Search Web"))
        self.labelEpisode.setText(_translate("MainWindow", "Episode"))
        self.episodeBrowser.setToolTip(_translate("MainWindow", "Current Episode"))
        self.labelWeb.setText(_translate("MainWindow", "Web Search"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuWindows.setTitle(_translate("MainWindow", "Windows"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))
        self.actionAbout.setText(_translate("MainWindow", "About Developer"))
        self.actionVersion.setText(_translate("MainWindow", "Version"))
        self.actionQuit_2.setText(_translate("MainWindow", "Open"))
        self.actionCalendar.setText(_translate("MainWindow", "Calendar"))
        self.actionCheck_for_updates.setText(_translate("MainWindow", "Check for updates."))
